Sprint 3
kkdras/middle.messenger.praktikum.yandex pull request #4
Opened 2023-03-12 21:55 UTC by kkdras

2023-03-13 13:11 UTC, evgenygil requested changes

2023-03-14 09:37 UTC, kkdras commented on src/client/controllers/chats.ts
> +			await promise;
Корявое задумка для того, чтобы метод getChatUsers выбрасывал ошибку навверх. Нужно было чтобы в allSettled отслеживать, когда выполнение действительно получилось неудачным. Ну сейчас я понимаю, что сделано бредово. Можно было просто поймать в catch, удалить loader и выбросить дальше.

2023-03-14 09:40 UTC, kkdras commented on src/client/pages/chat/components/addUserPopUp/index.ts
> +class _AddUserPopUp extends Block {
ну тк ниже он привязывается к стору и далее должен использоваться только привязанный класс. По аналогии с приватными полями класса

2023-03-14 09:46 UTC, kkdras commented on src/client/controllers/chats.ts
> +	const newMessage = message as IMessage | IMessage[];
Не вижу разницы где делать каст, либо изменять тип принимаемой функции в констркуторе ws на ...any, что по моему не очень правильно тк будет казаться, что аргумент будет именно того типа, который мы ожидаем в обработчике. Ну или здесь явно сделать каст, но зато осознанно

2023-03-14 09:52 UTC, kkdras commented on src/client/controllers/auth.ts
> +			removeLoader();
Обработку ошибок вообще стоит вынести в общий декоратор

2023-03-14 09:59 UTC, kkdras commented on src/client/store.ts
> +export const chatPageSelector = (store: StateType) => ({
Здесь просто описаны дефолтные значение по аналогии с defaultCase в Redux reducer, и в этом файле уже используется instance store для создания подписок и выборки данны. Абстрактная реализация самого хранилища никоим образом не мутируется и не модифицируется. Тоже и с Connect

2023-03-14 10:02 UTC, kkdras commented on src/client/controllers/chats.ts
> +		const { token } = await chatApi.createChatToken(id);
ну метод приватный используется только в публичных, которые не должны продолжать выполняться, если, например, токен не удалось создать. См пред comment

2023-03-14 10:03 UTC, kkdras commented on src/client/controllers/chats.ts
> +		Store.setState('chats.currentChat.id', 0);
можно

2023-03-14 10:08 UTC, kkdras commented on src/client/packages/Block.ts
> +		while (target && i > 0) {
Ну тут немного другая цель. Требуется найти эл по указанной вложенности

2023-03-14 10:14 UTC, kkdras commented on src/client/packages/Fetch.ts
> +	async request<T>(url: string, options: OptionsType, timeout = 5000) {
Согласен

2023-03-14 11:48 UTC, evgenygil commented on src/client/controllers/chats.ts
> +	const newMessage = message as IMessage | IMessage[];
Аргумент функции `message: unknown`, если он любого типа то зачем мы создаем еще одну константу по сути дублируя аргумент и уже указываем там ему тип, почему не написать `(message: IMessage | IMessage[]) => {..`, к чему тут вообще создание еще одной константы тут же равной аргументу

2023-03-14 11:49 UTC, evgenygil commented on src/client/controllers/auth.ts
> +			removeLoader();
Главное не переусложнить, либо вынести в общий либо использоваться finally просто и не дублировать `removeLoader()` в двух блоках и все, ничего такого в том что мы явно в каждом методе регулируем что мы там включаем или выключаем

2023-03-14 11:51 UTC, evgenygil commented on src/client/controllers/chats.ts
> +			await promise;
Для чего эти сложности? Можно написать просто последовательно обрабатывая ошибки с двух этих вызовов, с добавления юзера и получение юзеров по чату

2023-03-14 11:54 UTC, evgenygil commented on src/client/controllers/chats.ts
> +		const { token } = await chatApi.createChatToken(id);
Ну они может и не должны продолжать выполняться, но должны контролируемо упасть, независимо приватный это метод или публичный, если бы это была просто какая-то асинхронная функция то да, но тут явный вызов api, и сам этот метод где-то используется дальше, там будет непонятно на каком уровне вообще ошибка если просто повесить catch на все глобально

2023-03-14 11:58 UTC, evgenygil commented on src/client/interfaces/auth.d.ts
> +	declare interface body extends SignIn.body {
Это неважно, мы пишем код для человека, машина переварит все (главное валидное по синтаксису) а вот человеку который будет в последствии например что-то менять, рефакторить, и тут сущесвуют некоторые примерные практики, "как обычно делают", d.ts ы сгенерит сам тайпскрипт. Я не про namespace как обобщающую сущность, а про то, что это d.ts файл, они используются для другого обычно

2023-03-14 12:00 UTC, evgenygil commented on src/client/store.ts
> +export const chatPageSelector = (store: StateType) => ({
Так в том и дело, что если мы пишем абстрактный стор, логику сохранения, получения данных, здесь не должно быть каких-то дефолтных параметров сразу внутри, мы можем инициализировать стор с каким-то дефолтным набором, но это должно приходить снаружи.

2023-03-14 16:05 UTC, kkdras commented
Привет! Хотел отметить по поводу валидации, я конечно поправил кейс с login и display_name, но думаю, что в данном случае на это можно вообще закрыть глаза. Описание для поля display name вообще не дано.

По кейсу с изменением аватара были проблемы связаные с мутацией. (при попытке изменить подразумевается, что нужно сначала прикрепить, далее нажать на кнопку).

Кейс с юзером поправил, ошибка была в том, что промис не возвращался. И запросы удаления и получения списка шли паралельно.

Переход в проыиль через чат поправил.

Ну удаление себя из чата удаляет чат *у себя же. Думаю если это особо критично, то нужно править бек.

2023-03-14 16:27 UTC, kkdras commented on src/client/store.ts
> +export const chatPageSelector = (store: StateType) => ({
Ну в этом месте вызывается конструктор Store и Сonnector, а сами абстрактные классы хранятся в /packages/. Тут наверное не очень удачно выбрано имя файла, стоило назвать, например, app или storeInstance

2023-03-15 09:11 UTC, evgenygil commented on tsconfig.json
> +    "experimentalDecorators": true,                   /* Enable experimental support for TC39 stage 2 draft decorators. */
Сомневаюсь что стоит использовать декораторы пока они являются экспериментальной фичей, в продакшне, но это не критикал, так, jfyi

2023-03-15 09:45 UTC, kkdras commented on tsconfig.json
> +    "experimentalDecorators": true,                   /* Enable experimental support for TC39 stage 2 draft decorators. */
Ну тем не менее они используются в Ангуляре и Nest

2023-03-15 12:03 UTC, kkdras commented
![image](https://user-images.githubusercontent.com/69363856/225303088-f873710c-9d25-4332-bbc2-0e4628df8213.png)
У меня такой вопрос. Вы действительно думаете, что это можно отнести к серьезным замечаниям? По моему под критерий со второго спринта моя регулярка вполне подходит. Там не указывалось какие спец сиволы включать, а какие нет.

2023-03-15 12:55 UTC, evgenygil commented
> ![image](https://user-images.githubusercontent.com/69363856/225303088-f873710c-9d25-4332-bbc2-0e4628df8213.png)
> По моему под критерий со второго спринта моя регулярка вполне подходит. Там не указывалось какие спец сиволы включать, а какие нет.

Ну вот у меня есть пароль, он подходит по требованиям, которые я вижу на экране при заполнении формы, но в то же время он отбивается при сабмите, то есть залогиниться фактически я не могу

2023-04-01 01:19 UTC, kkdras commented
Обязательно проверте, что вышли из системы, то есть удалили куки для аутонтефикации.  Важно чтобы правильно работали редиректы по страницам

2023-04-01 08:49 UTC, evgenygil commented
> Обязательно проверте, что вышли из системы, то есть удалили куки для аутонтефикации. Важно чтобы правильно работали редиректы по страницам

Не очень понятно почему кука влияет на это, все такие ситуации надо обработать, иначе получается с уже имеющейся авторизацией всплывают какие-то артифакты. Не будет же такого что пользователю чата необходимо будет куда-то идти руками что-то удалять. Например при авторизации через апи, при переходе на ссылку чата появляется /notFound

2023-04-01 08:56 UTC, merged